server:
  port: 8080

spring:
  application:
    name: med
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/med?currentSchema=public
    username: postgres
    password: password
    driverClassName: org.postgresql.Driver
  liquibase:
    change-log: classpath:/db/changelog/changelog.xml
    enabled: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: orderbuyerzxc@gmail.com
    password: bhau wuvy rltg psgv
    properties:
      mail:
        smtp:
          starttls:
            enable: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 828349669244-uefk20ipds1eg22ks0n4m9aqj4hhrqcn.apps.googleusercontent.com
            client-secret: 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

minio:
  endpoint: http://127.0.0.1:9000
  accessKey:  minioadmin
  secretKey:  minioadmin
  bucket-name: commons